analyses:
  # - name: "Find Weak Classes for ResNet152 with Defocus Blur"
  #   type: "fragile_class"
  #   content:
  #     data:
  #       baseline: resnet152_imagenet.csv
  #       degraded: resnet152_imagenet_c_blur_defocus_blur_1.csv
  #   output_path: "analysis_results/resnet152_defocus_blur_1_weak_classes.json"


  - name: "resnet152_blur_defocus_blur_1"
    type: "accuracy_drop"
    content:
       data:
        baseline: resnet152_imagenet.csv
        corruption: resnet152_imagenet_c_blur_defocus_blur_1.csv

    - name: "resnet152_blur_defocus_blur_1"
    type: "accuracy_drop"
    content:
       data:
        baseline: resnet152_imagenet.csv
        corruption: resnet152_imagenet_c_blur_defocus_blur_1.csv
      
      