plots: 
  # - name: "imagenet_c_defocus_blur_1_spearman"
  #   type: "domain_spearman"
  #   title: "Spearman Correlation of per class accuracy drop - ImageNet-C Defocus Blur 1"
  #   x_label: ""
  #   y_label: ""
  #   output: "images/imagenet_c_defocus_blur_1_drop_spearman.png"
  #   content:
  #     metric_type: "drop"
  #     models:
  #       - name: "AlexNet"
  #         clean: "alexnet_imagenet.csv"
  #         corrupted: "alexnet_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ResNet-18"
  #         clean: "resnet18_imagenet.csv"
  #         corrupted: "resnet18_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ResNet-50"
  #         clean: "resnet50_imagenet.csv"
  #         corrupted: "resnet50_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ResNet-152"
  #         clean: "resnet152_imagenet.csv"
  #         corrupted: "resnet152_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "Wide-ResNet-50-2"
  #         clean: "wide_resnet50_2_imagenet.csv"
  #         corrupted: "wide_resnet50_2_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "Wide-ResNet-101-2"
  #         clean: "wide_resnet101_2_imagenet.csv"
  #         corrupted: "wide_resnet101_2_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ResNeXt-101-64x4d"
  #         clean: "resnext101_64x4d_imagenet.csv"
  #         corrupted: "resnext101_64x4d_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "DenseNet-121"
  #         clean: "densenet121_imagenet.csv"
  #         corrupted: "densenet121_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "EfficientNet-B0"
  #         clean: "efficientnet_b0_imagenet.csv"
  #         corrupted: "efficientnet_b0_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "EfficientNet-B4"
  #         clean: "efficientnet_b4_imagenet.csv"
  #         corrupted: "efficientnet_b4_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "RegNet-Y-16GF"
  #         clean: "regnet_y_16gf_imagenet.csv"
  #         corrupted: "regnet_y_16gf_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "MobileNet-V3-Large"
  #         clean: "mobilenet_v3_large_imagenet.csv"
  #         corrupted: "mobilenet_v3_large_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ViT-B/16"
  #         clean: "vit_b_16_imagenet.csv"
  #         corrupted: "vit_b_16_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ViT-L/16"
  #         clean: "vit_l_16_imagenet.csv"
  #         corrupted: "vit_l_16_imagenet_c_blur_defocus_blur_1.csv"
  #       # - name: "ViT-H/14"
  #       #   clean: "vit_h_14_imagenet.csv"
  #       #   corrupted: "vit_h_14_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "Swin-B"
  #         clean: "swin_b_imagenet.csv"
  #         corrupted: "swin_b_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "EfficientNet-V2-M"
  #         clean: "efficientnet_v2_m_imagenet.csv"
  #         corrupted: "efficientnet_v2_m_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ConvNeXt-Base"
  #         clean: "convnext_base_imagenet.csv"
  #         corrupted: "convnext_base_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "ConvNeXt-Large"
  #         clean: "convnext_large_imagenet.csv"
  #         corrupted: "convnext_large_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "Swin-V2-B"
  #         clean: "swin_v2_b_imagenet.csv"
  #         corrupted: "swin_v2_b_imagenet_c_blur_defocus_blur_1.csv"
  #       - name: "MaxVit-T"
  #         clean: "maxvit_t_imagenet.csv"
  #         corrupted: "maxvit_t_imagenet_c_blur_defocus_blur_1.csv"


  - name: "imagenet_c_defocus_blur_1_spearman"
    type: "domain_spearman"
    title: "Spearman Correlation of per class accuracy drop - ImageNet-C Defocus Blur 1"
    x_label: ""
    y_label: ""
    output: "images/imagenet_c_defocus_blur_1_rank_spearman.png"
    content:
      metric_type: "rank"
      models:
        - name: "AlexNet"
          clean: "alexnet_imagenet.csv"
          corrupted: "alexnet_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ResNet-18"
          clean: "resnet18_imagenet.csv"
          corrupted: "resnet18_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ResNet-50"
          clean: "resnet50_imagenet.csv"
          corrupted: "resnet50_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ResNet-152"
          clean: "resnet152_imagenet.csv"
          corrupted: "resnet152_imagenet_c_blur_defocus_blur_1.csv"
        - name: "Wide-ResNet-50-2"
          clean: "wide_resnet50_2_imagenet.csv"
          corrupted: "wide_resnet50_2_imagenet_c_blur_defocus_blur_1.csv"
        - name: "Wide-ResNet-101-2"
          clean: "wide_resnet101_2_imagenet.csv"
          corrupted: "wide_resnet101_2_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ResNeXt-101-64x4d"
          clean: "resnext101_64x4d_imagenet.csv"
          corrupted: "resnext101_64x4d_imagenet_c_blur_defocus_blur_1.csv"
        - name: "DenseNet-121"
          clean: "densenet121_imagenet.csv"
          corrupted: "densenet121_imagenet_c_blur_defocus_blur_1.csv"
        - name: "EfficientNet-B0"
          clean: "efficientnet_b0_imagenet.csv"
          corrupted: "efficientnet_b0_imagenet_c_blur_defocus_blur_1.csv"
        - name: "EfficientNet-B4"
          clean: "efficientnet_b4_imagenet.csv"
          corrupted: "efficientnet_b4_imagenet_c_blur_defocus_blur_1.csv"
        - name: "RegNet-Y-16GF"
          clean: "regnet_y_16gf_imagenet.csv"
          corrupted: "regnet_y_16gf_imagenet_c_blur_defocus_blur_1.csv"
        - name: "MobileNet-V3-Large"
          clean: "mobilenet_v3_large_imagenet.csv"
          corrupted: "mobilenet_v3_large_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ViT-B/16"
          clean: "vit_b_16_imagenet.csv"
          corrupted: "vit_b_16_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ViT-L/16"
          clean: "vit_l_16_imagenet.csv"
          corrupted: "vit_l_16_imagenet_c_blur_defocus_blur_1.csv"
        # - name: "ViT-H/14"
        #   clean: "vit_h_14_imagenet.csv"
        #   corrupted: "vit_h_14_imagenet_c_blur_defocus_blur_1.csv"
        - name: "Swin-B"
          clean: "swin_b_imagenet.csv"
          corrupted: "swin_b_imagenet_c_blur_defocus_blur_1.csv"
        - name: "EfficientNet-V2-M"
          clean: "efficientnet_v2_m_imagenet.csv"
          corrupted: "efficientnet_v2_m_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ConvNeXt-Base"
          clean: "convnext_base_imagenet.csv"
          corrupted: "convnext_base_imagenet_c_blur_defocus_blur_1.csv"
        - name: "ConvNeXt-Large"
          clean: "convnext_large_imagenet.csv"
          corrupted: "convnext_large_imagenet_c_blur_defocus_blur_1.csv"
        - name: "Swin-V2-B"
          clean: "swin_v2_b_imagenet.csv"
          corrupted: "swin_v2_b_imagenet_c_blur_defocus_blur_1.csv"
        - name: "MaxVit-T"
          clean: "maxvit_t_imagenet.csv"
          corrupted: "maxvit_t_imagenet_c_blur_defocus_blur_1.csv"